Upgraded to GCC8 on Debian Buster in GitLab CI to fix compilation issues
With GCC7, compiler throws errors:
src/edamer/dt/el_dist_matrix/impl.cpp:169:60: error: use of 'dist_ts' before deduction of 'auto'
    using columnwise_t = std::decay_t<decltype(hana::at_c<0>(dist_ts))>;